-- MySQL Script generated by MySQL Workbench
-- Sun 16 Feb 2020 02:13:45 CAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fertapp` DEFAULT CHARACTER SET utf8 ;
USE `fertapp` ;

-- -----------------------------------------------------
-- Table `mydb`.`lab_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`lab_results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `lab_number` VARCHAR(255) NOT NULL,
  `ref` VARCHAR(255) NOT NULL,
  `color` VARCHAR(3) NOT NULL,
  `texture` VARCHAR(4) NOT NULL,
  `pH` DECIMAL(3,2) NOT NULL,
  `free_carbonate` VARCHAR(1) NOT NULL,
  `conductivity` INT NOT NULL,
  `nitrogen` INT NOT NULL,
  `m_nitrogen_init` INT NOT NULL,
  `m_nitrogen_after` INT NOT NULL,
  `phosphorus` INT NOT NULL,
  `potasium` DECIMAL(5,2) NOT NULL,
  `calcium` DECIMAL(5,2) NOT NULL,
  `magnesium` DECIMAL(5,2) NOT NULL,
  `total_bases` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`crop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `regular_top_dressing` TINYINT(1) NOT NULL,
  `special_top_dressing` TINYINT(1) NOT NULL,
  `lowest_pH` DECIMAL(2,1) NOT NULL,
  `highest_pH` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recommendation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`recommendation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lab_number` INT NOT NULL,
  `ref` VARCHAR(45) NOT NULL,
  `nitrogen` VARCHAR(255) NOT NULL,
  `phosphorus` VARCHAR(255) NOT NULL,
  `potasium` VARCHAR(255) NOT NULL,
  `lime` VARCHAR(255) NOT NULL,
  `text1` VARCHAR(500),
  `text2` VARCHAR(500),
  `text3` VARCHAR(500),
  `text4` VARCHAR(500),
  `min_nitrogen` INT NOT NULL,
  `max_nitrogen` INT NOT NULL,
  `min_phosphorus` INT NOT NULL,
  `max_phosphorus` INT NOT NULL,
  `min_potasium` INT NOT NULL,
  `max_potasium` INT NOT NULL, 
  `crop` VARCHAR(90) NOT NULL,
  `nitrogen_fertilizer` VARCHAR(90) NOT NULL,
  `phosphorus_fertilizer` VARCHAR(90) NOT NULL,
  `potasium_fertilizer` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fertilizer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`fertilizer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nitrogen` DECIMAL(5,2) NOT NULL,
  `phosphorus` DECIMAL(5,2) NOT NULL,
  `potasium` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`crop_has_recommendation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`crop_has_recommendation` (
  `crop_id` INT NOT NULL,
  `recommendation_id` INT NOT NULL,
  PRIMARY KEY (`crop_id`, `recommendation_id`),
  INDEX `fk_crop_has_recommendation_recommendation1_idx` (`recommendation_id` ASC),
  INDEX `fk_crop_has_recommendation_crop1_idx` (`crop_id` ASC),
  CONSTRAINT `fk_crop_has_recommendation_crop1`
    FOREIGN KEY (`crop_id`)
    REFERENCES `fertapp`.`crop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crop_has_recommendation_recommendation1`
    FOREIGN KEY (`recommendation_id`)
    REFERENCES `fertapp`.`recommendation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lab_results_has_recommendation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`lab_results_has_recommendation` (
  `lab_results_id` INT NOT NULL,
  `recommendation_id` INT NOT NULL,
  PRIMARY KEY (`lab_results_id`, `recommendation_id`),
  INDEX `fk_lab_results_has_recommendation_recommendation1_idx` (`recommendation_id` ASC),
  INDEX `fk_lab_results_has_recommendation_lab_results1_idx` (`lab_results_id` ASC),
  CONSTRAINT `fk_lab_results_has_recommendation_lab_results1`
    FOREIGN KEY (`lab_results_id`)
    REFERENCES `fertapp`.`lab_results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lab_results_has_recommendation_recommendation1`
    FOREIGN KEY (`recommendation_id`)
    REFERENCES `fertapp`.`recommendation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crop_has_lab_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fertapp`.`crop_has_lab_results` (
  `crop_id` INT NOT NULL,
  `lab_results_id` INT NOT NULL,
  PRIMARY KEY (`crop_id`, `lab_results_id`),
  INDEX `fk_crop_has_lab_results_lab_results1_idx` (`lab_results_id` ASC),
  INDEX `fk_crop_has_lab_results_crop1_idx` (`crop_id` ASC),
  CONSTRAINT `fk_crop_has_lab_results_crop1`
    FOREIGN KEY (`crop_id`)
    REFERENCES `fertapp`.`crop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crop_has_lab_results_lab_results1`
    FOREIGN KEY (`lab_results_id`)
    REFERENCES `fertapp`.`lab_results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
